version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
  build:
    commands:
      - python -m pip install .
      - zip -r hubbleds.zip hubbleds
artifacts:
  files:
    - hubbleds.zip
